- name: retrieve facts
  hosts: base
  gather_facts: yes
  become: yes
  become_method: sudo
  vars_files: 
    - vars/vars.yml


  tasks:
  
  - name: Remove old file(s)
    ansible.builtin.file:
      path: "./{{ OUTPUT }}"
      state: absent

  - name: retrieve facts
    copy:
      content: "{{ ansible_facts }}"
      dest: "./{{ OUTPUT }}"
    delegate_to: localhost 

  - name: Check, Install if needed, Print and Log
    include_tasks: check.yml install.yml print.yml copy.yml  
    with_items: "{{CHECKS.OSS}}"
    loop_control:
      loop_var: SYS

# parsing
  - name: parse files to human readable form
    shell: tr , '\n' < "{{REDHAT_INSTALLED}}" | sed 's/"//g' | tee "{{OUTPUT_TMP}}"
    delegate_to: localhost

  #- name: execute parser
  #  shell: "{{ PARSER  }}"
    #delegate_to: localhost